[workspace]
members = ["blade-volume", "blade-volume-view", "blade-volume-convert"]
resolver = "2"

[workspace.dependencies]
blade-graphics = { git = "https://github.com/kvark/blade", rev = "e3cf011ca18a6dfd907d1dedd93e85e21f005fe3" }
blade-macros = "0.3"
bytemuck = "1"
glam = { version = "0.29", features = ["mint"] }
flate2 = "1.0"
half = "2"
log = "0.4"
mint = "0.5"
argh = "0.1"
env_logger = "0.11"
winit = "0.30"
kiddo = "4"
simple_delaunay_lib = "0.2"
