[package]
name = "blade-volume-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
blade-volume = { path = "../blade-volume" }
glam.workspace = true
gltf = { version = "1", features = ["import"] }
image = "0.25"
rand = "0.10"

[[bin]]
name = "convert"
path = "src/main.rs"

[lints]
workspace = true
