[package]
name = "blade-volume-test"
version = "0.1.0"
edition = "2021"

[dependencies]
blade-graphics.workspace = true
blade-volume = { path = "../blade-volume" }
blade-volume-convert = { path = "../blade-volume-convert" }
blade-volume-view = { path = "../blade-volume-view" }
glam.workspace = true
half.workspace = true
image = "0.25"
