[package]
name = "blade-volume"
version = "0.1.0"
edition = "2021"

[dependencies]
blade-graphics.workspace = true
blade-macros.workspace = true
bytemuck.workspace = true
glam.workspace = true
flate2.workspace = true
kiddo.workspace = true
log.workspace = true
mint.workspace = true
qhull.workspace = true

simple_delaunay_lib.workspace = true

[dev-dependencies]
half.workspace = true

[lints]
workspace = true
